type DeliveryOption {
    id: Int!
    title: String!
    price: Int!
    default: Boolean!
}

type DiscountCode {
    id: Int!
    code: String
    discount: Int
    type: String
}

type Item {
    id: Int!
    title: String!
    seller: String!
    price: Int!
    image: String!
    delivery: [DeliveryOption]!
}

type User {
    id: Int!
    email: String!
    password: String!
    name: String
    phone: String
    addressLine: String
    town: String
    postcode: String
}

type UserLoginResponse {
    success: Boolean!
    message: String
    user: [User]
}

type Mutation {
    login(email: String!): UserLoginResponse!
    register(
        email: String!
        name: String
        phone: String
        addressLine: String
        town: String
        postcode: String
    ): UserLoginResponse!
}

type Query {
    items: [Item]
    discountCodes: [DiscountCode]
    discountCode(code: String!): DiscountCode
}
